name: Test

on: [push, workflow_dispatch]

jobs:
  run-script-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install opam
        run: sudo apt install opam; opam init

      - name: Run script.sh
        run: bash ./script.sh

      - name: Run manual.sh
        run: bash ./manual.sh
