name: Test

on: [push, workflow_dispatch]

jobs:
  run-local:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install opam
        run: sudo apt install opam; opam init

      - name: Create opam switch
        run: opam switch create 4.14.2

      - name: Run script.sh
        run: bash ./script.sh

      - name: Run manual.sh
        run: bash ./manual.sh

  run-rocq:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        coq_version:
          - dev
          - 9.1
        ocaml_version: ["default"]
      max-parallel: 4
      fail-fast: false

    steps:
      - uses: actions/checkout@v6
      - uses: coq-community/docker-coq-action@v1
        with:
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: "default"
          opam_file: "x.opam"
          custom_script: |
            sudo apt-get update -y
            sudo apt-get upgrade -y
            opam config list
            opam repo list
            git config --global core.logAllRefUpdates true
            export GIT_TRACE=1
            opam pin -j1 add -vv -n -y -k path $PACKAGE $WORKDIR
            opam pin -j1 add -n -k path $PACKAGE $WORKDIR # maybe this'll cause CI failure if the first thing errors?
